{
    "version": "0.1",
    "author": "Tarek Berkane",
    "maintainer": "Tarek Berkane",
    "name": "Payment Provider: Chargily",
    "summary": "A payment provider in Algeria.",
    "description": "Chargily Pay, a gateway that allows you to accept online payments with many payment methods in Algeria such as EDAHABIA and CIB cards. ",
    "category": "Accounting/Payment Providers",
    "sequence": 400,
    "license": "LGPL-3",
    "depends": ["payment"],
    "data": [
        "views/payment_chargily_templates.xml",
        "views/payment_provider_views.xml",
        "data/payment_method_data.xml",
        "data/payment_provider_data.xml",
    ],
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
}
